services:
  autygo-api:
    container_name: autygo-api
    build:
      context: ./backend
      args:
        MODE: test     # ou "prod".
    ports:
      - "${BACK_PORT}:80"
    volumes:
      - ./backend:/var/www/app
    depends_on:
      - mysql_db

  autygo-frontend:
    container_name: autygo-frontend
    build:
      context: ./frontend
      args:
        MODE: test     # ou "prod".
    ports:
      - "${FRONT_PORT}:80"
    volumes:
      - ./frontend:/app

  autygo-tests:
    container_name: autygo-tests
    build:
      context: ./tests
      args:
        MODE: test      # ou prod
    volumes:
      - ./tests:/autygo-tests

  mysql_db:
    image: mysql:8.3
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: autygo-phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: mysql_db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql_db
    platform: linux/amd64


volumes:
  mysql_data:

